name: Pytest

on:
  push:
    paths:
      - "**"
      - "!**.md"
      - "!**LICENSE"
      - "!**.gitignore"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/unit-tests.yaml"
  pull_request:
    paths:
      - "**"
      - "!**.md"
      - "!**LICENSE"
      - "!**.gitignore"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/unit-tests.yaml"

jobs:
  unit-tests:
    name: Pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-20.04 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3.10.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Prerequisites
        run: sudo apt install python3-pytest pylint

      - name: versions
        run: |
          python --version
          pytest --version

      - name: Running tests
        run: |
          cd test
          pytest

      - name: Pylint - configs
        if: success() || failure()
        run: |
          cd configs
          pylint --rcfile .pylintrc *

      - name: Pylint
        if: success() || failure()
        run: pylint --rcfile .pylintrc *

      - name: Pylint - test
        if: success() || failure()
        run: |
          cd test
          pylint --rcfile .pylintrc *
