name: Pytest

on:
  push:
    paths:
      - "**"
      - "!**.md"
      - "!**LICENSE"
      - "!**.gitignore"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/unit-tests.yaml"
  pull_request:
    paths:
      - "**"
      - "!**.md"
      - "!**LICENSE"
      - "!**.gitignore"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/unit-tests.yaml"

env:
  PYTHONPATH: `pwd`

jobs:
  unit-tests:
    name: Pytest on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python 3.10.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.7'

      - name: Install Prerequisites
        run: |
          sudo apt --yes install python3-pytest pylint
          sudo apt --yes install --only-upgrade python3-pytest pylint

      - name: Versions
        run: |
          python --version
          pytest-3 --version
          echo "Pylint:"
          pylint --version

      - name: Running tests
        run: |
          pwd
          pytest-3

      - name: Pylint - configs
        if: success() || failure()
        run: |
          cd configs
          pylint --rcfile .pylintrc *

      - name: Pylint - src
        if: success() || failure()
        run: pylint --rcfile .pylintrc *

      - name: Pylint - test
        if: success() || failure()
        run: |
          cd test
          pylint --rcfile .pylintrc *
